name: Deploy react app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "14.x" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: yarn install
      - name: registry github user
        run: |
          git config --global user.email miguel.moralesr@hotmail.com
          git config --global user.name "Miguel Angel Morales R."
      - name: deploy the app
        run: yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}